name: Build and Test Pull Requests

on:
  pull_request:
    branches:
    - master

jobs:  
  build:
    name: "Build and Test Pull Requests"
    env:
        ANDROID_HOME: "/Users/runner/Library/Android/sdk"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    - run: adb devices
    - run: echo $ANDROID_HOME
    - run: |
          cd $ANDROID_HOME/tools/bin
          ./sdkmanager "build-tools;29.0.2"
    
    - name: Setup Nuget
      uses: olegtarasov/download-nuget@v1
          
    - name: Restore Nuget Packages
      run: mono $NUGET_EXE restore TransactionMobile/TransactionMobile.sln -source "https://api.nuget.org/v3/index.json;https://www.myget.org/F/transactionprocessing/api/v3/index.json"

    - name: Build Code
      run: msbuild /p:Configuration="Release" /p:Platform="iPhoneSimulator" /t:Build TransactionMobile/TransactionMobile.sln

    - name: Run Unit Tests
      run: mono /Users/runner/runners/2.163.1/work/MobileApplication/MobileApplication/TransactionMobile/packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe TransactionMobile/TransactionMobile.UnitTests/bin/Release/TransactionMobile.UnitTests.dll

    - name: Build APK
      run: msbuild TransactionMobile/TransactionMobile.Android/TransactionMobile.Android.csproj -target:SignAndroidPackage /p:Configuration=Release
            
    - name: Setup Docker
        run: |
          brew install docker-machine docker
          sudo docker –version

    - name: Run Integration Tests - Android
      uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
      with:
          cmd: mono /Users/runner/runners/2.163.1/work/MobileApplication/MobileApplication/TransactionMobile/packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe TransactionMobile/TransactionMobile.IntegrationTests/bin/Release/TransactionMobile.IntegrationTests.dll --where "cat == Android"
          api: 29
          tag: default
          abi: x86
    
    - name: Run Integration Tests - iOS
      run: mono /Users/runner/runners/2.163.1/work/MobileApplication/MobileApplication/TransactionMobile/packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe TransactionMobile/TransactionMobile.IntegrationTests/bin/Release/TransactionMobile.IntegrationTests.dll --where "cat == iOS"
    
    - name: Setup tmate session
      if: failure()
      uses: mxschmitt/action-tmate@v1
