name: Build and Test Pull Requests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: "Build and Test Pull Requests - Android"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Restore Nuget Packages
      run: nuget restore TransactionMobile\TransactionMobile.sln

    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build Code
      run: msbuild TransactionMobile\TransactionMobile.sln -p:Configuration=Release

    - name: Run Unit Tests
      run: D:\a\MobileApplication\MobileApplication\TransactionMobile\packages\xunit.runner.console.2.4.1\tools\net472\xunit.console.exe TransactionMobile\TransactionMobile.UnitTests\bin\Release\TransactionMobile.UnitTests.dll
      
    - name: Build APK
      run: msbuild TransactionMobile\TransactionMobile.Android\TransactionMobile.Android.csproj -target:SignAndroidPackage /p:Configuration=Release
      
    #- name: Run Integration Tests
    #  run: D:\a\MobileApplication\MobileApplication\TransactionMobile\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe TransactionMobile\TransactionMobile.IntegrationTests\bin\Release\TransactionMobile.IntegrationTests.dll --where "cat == Android"
    - name: Run Integration Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: D:\a\MobileApplication\MobileApplication\TransactionMobile\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe TransactionMobile\TransactionMobile.IntegrationTests\bin\Release\TransactionMobile.IntegrationTests.dll --where "cat == Android"
      
